olix_back_office_bundle.routes:
    type: attribute
    resource: '@OlixBackOfficeBundle/src/Controller/'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"
