services:

    olix.backoffice.twig.extension:
        class: Olix\BackOfficeBundle\Twig\BackOfficeExtension
        tags:
            - { name: twig.extension }

    olix.backoffice.twig.runtime:
        class: Olix\BackOfficeBundle\Twig\BackOfficeRuntime
        arguments: [ '%olix_back_office%' ]
        tags:
            - { name: twig.runtime }

    olix.backoffice.twig.events:
        class: Olix\BackOfficeBundle\Twig\EventsRuntime
        arguments: [ '@event_dispatcher' ]
        tags:
            - { name: twig.runtime }

    Olix\BackOfficeBundle\Security\UserChecker:

    Olix\BackOfficeBundle\Security\UserManager:
        arguments: [ '@service_container', '@parameter_bag', '@doctrine', '@security.user_password_hasher' ]

    Olix\BackOfficeBundle\Listener\LoginListener:
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    Olix\BackOfficeBundle\Controller\:
        resource: '../src/Controller'
        arguments: ['@parameter_bag']
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]

    Olix\BackOfficeBundle\Form\Type\Select2AjaxType:
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type }

    Olix\BackOfficeBundle\Twig\DatatableRuntime:
        public: false
        tags:
            - { name: twig.runtime }

    Olix\BackOfficeBundle\Datatable\Response\DatatableResponse:
        public: true
        arguments:
            - '@request_stack'
