services:

    olix.backoffice.twig.extension:
        class: Olix\BackOfficeBundle\Twig\BackOfficeExtension
        tags:
            - { name: twig.extension }

    olix.backoffice.twig.runtime:
        class: Olix\BackOfficeBundle\Twig\BackOfficeRuntime
        arguments: [ '%olix_back_office%' ]
        tags:
            - { name: twig.runtime }

    olix.backoffice.twig.events:
        class: Olix\BackOfficeBundle\Twig\EventsRuntime
        arguments: [ '@event_dispatcher' ]
        tags:
            - { name: twig.runtime }

    Olix\BackOfficeBundle\Security\UserChecker:

    Olix\BackOfficeBundle\Listener\LoginListener:
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    Olix\BackOfficeBundle\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]