parameters:
    olix.backup.path.default: /tmp
    olix.backup.path: '%env(default:olix.backup.path.default:string:BACKUP_PATH)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $kernelProjectDir: '%kernel.project_dir%' 
            $pathRootBackup: '%olix.backup.path%' # Racine des backups pour les commandes de sauvegarde/restauration
            $olixConfigParameter: '%olix_back_office%' # Configuration du bundle (config/olix_bo.yml)
    
    Olix\BackOfficeBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/'
            - '../src/Tests/'

    Twig\Extension\StringLoaderExtension:
        tags: [twig.extension]
